Add a `phpcs.xml.dist` file for PHP file formatting standards
wp-cli/wp-cli-dev pull request #35
Opened 2022-08-12 14:52 UTC by danielbachhuber

2022-08-12 15:33 UTC, schlessera commented
What is the purpose of this ruleset? To lint the PHP logic added to this repo specifically (like the maintenance commands), or to lint the entire bundle?
I don't think linting the entire bundle is useful, it will just block commits for no reason. Also, it would mean keeping the package-specific exclusions in merged sync with all packages.
The ruleset should instead point to the `.maintenance` folder only, where the PHP files specific to this repository are. It should then only include the rule exclusions that are needed for that part of the code.

2022-08-12 16:05 UTC, danielbachhuber commented
> What is the purpose of this ruleset? To lint the PHP logic added to this repo specifically (like the maintenance commands), or to lint the entire bundle?

@schlessera The former: linting the maintenance commands.

> The ruleset should instead point to the `.maintenance` folder only, where the PHP files specific to this repository are. It should then only include the rule exclusions that are needed for that part of the code.

My bad. I copied the `phpcs.xml.dist` from `wp-cli/wp-cli` because I thought we might want to keep them in sync in some fashion.

To make sure we're on the same page, can you annotate the PR with the changes you'd suggest?

2022-08-12 16:47 UTC, schlessera requested changes

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +	<description>Custom ruleset for WP-CLI</description>
Each ruleset has a distinct name so we can keep them apart.
```suggestion
<ruleset name="WP-CLI-Dev">
	<description>Custom ruleset for the WP-CLI development environment</description>
```

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +	<file>.</file>
You'll have to test the exact syntax here, but probably something like this:
```suggestion
	<file>./.maintenance/</file>
```

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +
We don't have any tests specific to this package.
```suggestion
```

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +	</rule>
Probably no exceptions needed here:
```suggestion
	<rule ref="WP_CLI_CS"/>
```

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +
These exceptions should not be needed. We might need different ones, though...
```suggestion
```

2022-08-12 16:47 UTC, schlessera commented on phpcs.xml.dist
> +
These exceptions should not be needed. We might need different ones, though...
```suggestion
```

2022-08-16 20:06 UTC, danielbachhuber commented
@schlessera It doesn't look like `composer phpcs` works as expected locally...

```
$ composer phpcs
> run-phpcs-tests
sh: run-phpcs-tests: command not found
Script run-phpcs-tests handling the phpcs event returned with error code 127
```

Thoughts on how I should continue to iterate?

Also, should I avoid cloning all of the package repos [in the job](https://github.com/wp-cli/wp-cli-dev/runs/7865981070?check_suite_focus=true)?

<img width="550" alt="image" src="https://user-images.githubusercontent.com/36432/184974807-25eff26c-e634-4567-a536-994946997d1e.png">

2022-08-17 06:51 UTC, schlessera commented
`run-phpcs-tests` is part of `wp-cli/wp-cli-tests`, so you'd need to pull that in as a development dependency. Not sure what that will produce given the symlinky madness in this package, you'll have to try and see. The `wp-cli/wp-cli-tests` also provides the main PHPCS ruleset you're extending, so you'd need it either way for PHPCS to work correctly.

Regarding the cloning, I guess it would make sense to have the action go through the entire flow. I'm just surprised that GitHub itself has trouble cloning these publicly accessible packages...?!

2022-10-13 22:16 UTC, danielbachhuber commented
@schlessera This is fixed up now.

2022-10-27 15:12 UTC, schlessera approved these changes

2022-10-27 15:12 UTC, merged